#BASE_PATH=$(shell pwd)
BASE_PATH=.

CC=g++
CFLAGS= -g -c
LD_FLAGS= -lgtest -lgtest_main -lgmock -lgmock_main -lpthread
LCOV_FLAGS= -fprofile-arcs -ftest-coverage -g 

BUILD_OUTPUT_PATH=$(BASE_PATH)/build
OBJECT_PATH=$(BUILD_OUTPUT_PATH)/obj
BINARY_PATH=$(BUILD_OUTPUT_PATH)/bin
LIB_PATH=$(BUILD_OUTPUT_PATH)/lib
